- hosts: all

  tasks:
  - name: Download maven
    get_url:
      url: http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
      dest: /etc/yum.repos.d/epel-apache-maven.repo
      validate_certs: no
      timeout: 60
      mode: 0777

  - replace:
      path: /etc/yum.repos.d/epel-apache-maven.repo
      regexp: '\$releasever/'
      replace: '6/'
      backup: yes

  - name: Install apache maven
    yum:
      name: apache-maven
      state: latest
